development:
  adapter: redis
  url: redis://cache:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CACHE") { "redis://cache:6379/1" } %>
  channel_prefix: chat_production
